/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;

import static org.junit.Assert.*;
// resources:
// https://www.baeldung.com/junit-src-test-resources-directory-path
// https://www.baeldung.com/java-assert-string-not-empty

// Use JUnit to write a test for the linter.
// You’ll need to create a JS file that will test each of these things!

public class AppTest {
    // Test the linter on a file that contains no errors.
    @Test public void testAppLinterNoError() {
    String input = "resources/noError.js";
    String actual = App.linterFilter(input);
        assertEquals(actual, "");
    }

    // Test the linter on a file that contains one error.
    @Test public void testAppLinterOneError() {
        String input = "resources/oneError.js";
        String actual = App.linterFilter(input);
        String expected = "Line 2: Missing semicolon.\n";
        assertEquals(actual, expected);
    }

    // Test the linter on a file that contains few errors.
    @Test public void testAppLinterFewErrors() {
        String input = "resources/fewErrors.js";
        String actual = App.linterFilter(input);
        String expected = "Line 2: Missing semicolon.\nLine 6: Missing semicolon.\n";
        assertEquals(actual, expected);
    }

    // Test the linter on a file that contains many errors.
    @Test public void testAppLinterManyErrors() {
        String input = "resources/manyErrors.js";
        String actual = App.linterFilter(input);
        String expected = "Line 2: Missing semicolon.\n" +
                "Line 6: Missing semicolon.\n" +
                "Line 10: Missing semicolon.\n" +
                "Line 14: Missing semicolon.\n" +
                "Line 18: Missing semicolon.\n" +
                "Line 22: Missing semicolon.\n" +
                "Line 26: Missing semicolon.\n" +
                "Line 30: Missing semicolon.\n" +
                "Line 34: Missing semicolon.\n" +
                "Line 38: Missing semicolon.\n";
        assertEquals(actual, expected);
    }

    // Test the linter on an empty file.
    @Test public void testAppLinterEmptyFile() {
        String input = "resources/emptyFile.js";
        String actual = App.linterFilter(input);
        assertTrue(actual.isEmpty());
    }
}
