/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
// Resource:
// https://www.w3schools.com/java/java_files_read.asp

public class App {

    public static void main(String[] args) {
        System.out.println(linterFilter("resources/gates.js"));
    }

    public static String linterFilter(String args){
        String result = "";
        int line = 1;
        try {
            File objFile = new File(args);
            Scanner reader = new Scanner(objFile);
            line += 0;
            while (reader.hasNextLine()) {
                String data = reader.nextLine();
                if(!data.contains("{") && !data.contains("}") && !data.contains("if") && !data.contains("else") && !data.isEmpty() && !data.endsWith(";")){
                    result += "Line " + line + ": Missing semicolon.\n";
                    line++;
                }
                else{
                    line++;
                }
            }
            reader.close();
        } catch (FileNotFoundException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }
        return result;
    }
}

