/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {

    @Test public void testRoll(){
        int input = 4;
        int[] expected = Library.roll(input);
        assertEquals(input, expected.length);
    }

    @Test public void testContainsDuplicates(){
        String[] input = {"a", "b", "c", "a"};
        boolean expected = true;
        assertEquals(input, expected);
    }
}
