/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.*;

// assertEquals(actual, assert, delta);
public class LibraryTest {

    @Test public void testRoll(){
        int input = 4;
        int[] expected = Library.roll(input);
        assertEquals(input, expected.length);
    }

    @Test public void rollBetween1and6(){
        int[] expected = Library.roll(4);
        for(int num : expected){
            boolean actual = num > 0 && num < 7;
            assertTrue(actual);
        }
    }

    @Test public void testContainsDuplicates(){
        String[] input = {"a", "b", "c", "a"};
        boolean actual = Library.containsDuplicates(input);
        boolean expected = true;
        assertEquals(actual, expected);
    }

    @Test public void testNoContainDuplicates(){
        String[] input = {"a", "b", "c"};
        boolean actual = Library.containsDuplicates(input);
        boolean expected = false;
        assertEquals(actual, expected);
    }

    @Test public void testCalculatingAverage(){
        int[] input = {1, 2, 3, 4, 5};
        int actual = Library.calculatingAverage(input);
        int expected = 3;
        assertEquals(actual,expected);
    }

    @Test public void testArrayAverage(){
        int[][] input = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int actual = Library.arrayAverage(input);
        int expected = 57;
        assertEquals(actual, expected);
    }

    @Test public void testMapi(){
        int [][] input = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        String actual = Library.mapi(input);
        String expected = "High: 72\n" +
                "Low: 51\n" +
                "Never saw temperature: 63\n" +
                "Never saw temperature: 67\n" +
                "Never saw temperature: 68\n" +
                "Never saw temperature: 69\n";
        assertEquals(actual, expected);
    }

    @Test public void testTally(){
        List<String> input = new ArrayList<>();
        input.add("Bush");
        input.add("Bush");
        input.add("Bush");
        input.add("Shrub");
        input.add("Hedge");
        input.add("Shrub");
        input.add("Bush");
        input.add("Hedge");
        input.add("Bush");
        String actual = Library.tally(input);
        String expected = "Bush received the most votes!";
        assertEquals(actual, expected);
    }

}
