/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.Arrays;
import java.util.Random;

public class Library {
//    public boolean someLibraryMethod() {
//        return true;
//    }
    public static void main(String[] args){
        // run method to see results
    }

    //Write a method called roll that accepts an integer n and rolls a six-sided dice n times.
    // The method should return an array containing the values of the rolls.
    static int[] roll(int n){
        Random randgen = new Random();
        int[] newArr = new int[n];

        for (int i = 0; i < n; i++){
            newArr[i] = randgen.nextInt(6);
        }
        System.out.println(Arrays.toString(newArr));
        return newArr;
    }

    //Write a method called containsDuplicates that returns true or false
    // depending on whether the array contains duplicate values.
    static boolean containsDuplicates( String[] args){
        boolean result = true;
        for (int i = 0; i < args.length; i++) {
            for (int j = args.length - 1; j >= 0; j--){
                if (args[i] == args[j]) {
                    return result;
                } else {
                    return result = false;
                }
            }
        }
        return result;
    }

    //Calculating Averages: Write a method that accepts an array of integers and calculates and
    // returns the average of all the values in the array.

    // Arrays of Arrays: Given an array of arrays calculate the average value for each array
    // and return the array with the lowest average.
}
